### ISSUE TITLE
Привет. А где твой финальный проект. Репозиторий пустой! Hello. Where is your final project. The repository is empty!

### ISSUE THREAD

**Issue by agony30** [MariyaZavarzina/final_task_autotest_curse#1]
Привет. Мне на ревью в Stepik попал твой проект. Но в нём нет никаких файлов из заданий. Как проверять?
Hello. I got your project for a review in Stepik. There are no files from the tasks in it. How to check?

Подожду 24 часа твоего ответа, после этого поставлю 0 баллов.
I will wait 24 hours for your answer, after that I will put 0 points.

![image](https://user-images.githubusercontent.com/45768380/191480678-e325ff1a-7d52-4a88-814a-50e50a81a860.png)

**Comment by MariyaZavarzina** [comment]
Привет. Весь проект не в основной ветке, а во второй для удобства.
Hello. The whole project is not in the main branch, but in the second for convenience.
<img width="675" alt="Screenshot_1" src="https://user-images.githubusercontent.com/108276645/191485050-ec99cdcd-0fdc-4c52-902a-ff60abd56b27.png">
<img width="335" alt="Screenshot_2" src="https://user-images.githubusercontent.com/108276645/191485065-02af3b13-e960-46d3-b09a-93956f76a7b7.png">
<img width="698" alt="Screenshot_3" src="https://user-images.githubusercontent.com/108276645/191485072-4e70e37e-497e-409d-9511-d88123dc4c4d.png">

**Comment by agony30** [comment]
Ок. Про ветки не подумал. Нашёл. )Но для удобства кому? Это же не такой большой проект, что бы бояться поместить его в основную ветку. Кто нибудь из ревьюиров не станет разбираться, и проставит 0 баллов.

**Comment by MariyaZavarzina** [comment]
Решила сделать так, чтобы потом в этот же проект добавить еще тестов. Другие ревьюеры уже проверили, остался только 1 ревью ;)

**Comment by agony30** [comment]
в файле login_page.py что за модуль такой?
from **random_word** import RandomWords

**Comment by agony30** [comment]
другие ревьюеры максимально поставили?

**Comment by agony30** [comment]
Не могу найти такой модуль
![image](https://user-images.githubusercontent.com/45768380/191493985-faa1d9a3-e640-4942-a970-c9251067d65d.png)

**Comment by MariyaZavarzina** [comment]
пакет Python для генерации случайных английских слов

**Comment by MariyaZavarzina** [comment]
Да, максимально

**Comment by agony30** [comment]
Всё проверил. По баллам максималка. Комментарии допишу, и закрою.
От себя хотел спросить. Зачем файл __init__ в каждой папке? Это как то импорт облегчает?

**Comment by agony30** [comment]
И я не смог запустить тесты с указанием языка **--en**. Только через команду **pytest -v --tb=line -m need_review** - пока пытаюсь разобраться, почему. Но подозрение на разные версии Python

**Comment by MariyaZavarzina** [comment]
Привет. Весь проект не в основной ветке, а во второй для удобства.
Hello. The whole project is not in the main branch, but in the second for
convenience.

ср, 21 сент. 2022 г. в 12:23, agony30 ***@***.***>:
